"use client"
import './globals.css'
import Wrapper from '@/components/wrapper/Wrapper'
import { store } from '@/store/store'
import { Provider } from 'react-redux'
import bootstrap from '../node_modules/bootstrap/dist/css/bootstrap.min.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Wrapper>
           {children}
        </Wrapper>
      </body>
    </html> 
  )
}
